import type { Project } from '../types'

export const projects: Project[] = [
  {
    id: 1,
    titleKey: 'projects.items.defi.title',
    descriptionKey: 'projects.items.defi.description',
    tags: ['Next.js', 'Solidity', 'Tailwind'],
    techStackKeys: [
      'nextjs',
      'typescript',
      'react',
      'tailwindcss',
      'nestjs',
      'nodejs',
      'rust',
      'postgres',
      'redis',
    ],
    type: 'featured',
    image: '/CoinFi.png',
    caseStudyKey: 'projects.items.defi.caseStudy',
  },
  {
    id: 2,
    titleKey: 'projects.items.neural.title',
    descriptionKey: 'projects.items.neural.description',
    tags: ['Python', 'PyTorch'],
    techStackKeys: ['python'],
    categoryKey: 'projects.items.neural.category',
    type: 'featured',
    image: '/CoinFi.png',
  },
  {
    id: 3,
    titleKey: 'projects.items.saas.title',
    descriptionKey: 'projects.items.saas.description',
    tags: ['React', 'Node.js', 'MongoDB'],
    techStackKeys: ['react', 'nodejs'],
    type: 'featured',
    statKey: 'projects.items.saas.stat',
    image: '/CoinFi.png',
  },
  {
    id: 4,
    titleKey: 'projects.items.fintech.title',
    descriptionKey: 'projects.items.fintech.description',
    tags: ['TypeScript', 'PostgreSQL'],
    techStackKeys: ['typescript', 'postgres'],
    type: 'featured',
    image: '/CoinFi.png',
  },
]
