import type { TechStackItem } from '../types'

export const techStack: TechStackItem[] = [
  { logo: '/tech-logos/python.svg', altKey: 'python' },
  { logo: '/tech-logos/rust.svg', altKey: 'rust' },
  { logo: '/tech-logos/java.svg', altKey: 'java' },
  { logo: '/tech-logos/typescript.svg', altKey: 'typescript' },
  { logo: '/tech-logos/nodejs.svg', altKey: 'nodejs' },
  { logo: '/tech-logos/nestjs.svg', altKey: 'nestjs' },
  { logo: '/tech-logos/html5.svg', altKey: 'html5' },
  { logo: '/tech-logos/css3.svg', altKey: 'css3' },
  { logo: '/tech-logos/javascript.svg', altKey: 'javascript' },
  { logo: '/tech-logos/react.svg', altKey: 'react' },
  { logo: '/tech-logos/vite.svg', altKey: 'vite' },
  { logo: '/tech-logos/nextjs.svg', altKey: 'nextjs' },
  { logo: '/tech-logos/tailwind-css.svg', altKey: 'tailwindcss' },
  { logo: '/tech-logos/vue.svg', altKey: 'vue' },
  { logo: '/tech-logos/figma.svg', altKey: 'figma' },
  { logo: '/tech-logos/postgres.svg', altKey: 'postgres' },
  { logo: '/tech-logos/redis.svg', altKey: 'redis' },
  { logo: '/tech-logos/aws.svg', altKey: 'aws' },
  { logo: '/tech-logos/google-cloud.svg', altKey: 'googleCloud' },
  { logo: '/tech-logos/azure.svg', altKey: 'azure' },
  { logo: '/tech-logos/kubernetes.svg', altKey: 'kubernetes' },
  { logo: '/tech-logos/terraform.svg', altKey: 'terraform' },
  { logo: '/tech-logos/docker.svg', altKey: 'docker' },
  { logo: '/tech-logos/digital-ocean.svg', altKey: 'digitalOcean' },
  { logo: '/tech-logos/grafana.svg', altKey: 'grafana' },
]
